#!/usr/bin/env python3
"""Consolidate SeaVigil's accuracy measurements into one honest report (docs/MEASUREMENT.md).

Pulls together recall on real IUU vessels (scripts/validate_iuu.py), the precision/recall of the IUU
cross-reference (scripts/measure_iuu_xref.py), and the deployed system's authorization-grading
distribution on the real monitored fleet, and states plainly the false-positive bound that public data
cannot cross. SeaVigil produces inspection leads, not verdicts; this page is honest about which parts of
that claim are measured and which are fundamentally unmeasurable from public data.

    uv run python scripts/build_measurement.py
"""

from __future__ import annotations

import json
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT_MD = ROOT / "docs" / "MEASUREMENT.md"
OUT_JSON = ROOT / "results" / "measurement.json"


def _load(rel: str):
    p = ROOT / rel
    return json.loads(p.read_text()) if p.exists() else None


def _auth_distribution() -> Counter:
    c: Counter = Counter()
    for view in ("live", "incidents"):
        for d in (_load(f"results/{view}/incidents.json") or []):
            if d.get("authorization_status"):
                c[d["authorization_status"]] += 1
    return c


def main() -> None:
    val = (_load("results/validation.json") or {}).get("summary")
    xref = _load("results/iuu_xref_measure.json")
    auth = _auth_distribution()
    tot = sum(auth.values())
    cleared = auth.get("authorized", 0) + auth.get("domestic", 0)
    flagged = auth.get("no_record", 0) + auth.get("authorization_lapsed", 0)

    measurement = {
        "recall_on_iuu_vessels": val,
        "iuu_xref_precision_recall": xref and {k: xref.get(k) for k in
            ("recall_by_imo", "recall_by_alias_name", "name_collision_risk", "negative_control")},
        "authorization_grading_on_fleet": {"n": tot, **dict(auth),
            "cleared_pct": round(100 * cleared / tot) if tot else None,
            "flagged_for_review_pct": round(100 * flagged / tot) if tot else None},
    }
    OUT_JSON.parent.mkdir(parents=True, exist_ok=True)
    OUT_JSON.write_text(json.dumps(measurement, indent=1))
    OUT_MD.write_text(_render(val, xref, auth, tot, cleared, flagged))
    print(f"wrote {OUT_MD} and {OUT_JSON}")
    print(json.dumps(measurement["authorization_grading_on_fleet"], indent=1))


def _render(val, xref, auth, tot, cleared, flagged) -> str:
    L = ["# Measuring SeaVigil: how good are the leads?\n",
         "> Generated by `scripts/build_measurement.py`. Re-run to refresh.\n",
         "SeaVigil produces inspection **leads, not verdicts**. This reports what can be measured from "
         "public data, and is honest about what cannot.\n"]

    L.append("## Recall: does it catch known IUU vessels?\n")
    if val:
        t, r = val["total"], val["gfw_resolved"]
        na, it = val["resolved_with_no_current_authorization"], val["gfw_iuu_tagged"]
        L.append(f"Ground truth: the [CCAMLR Non-Contracting-Party IUU list]"
                 f"({val.get('ground_truth_url', '')}), an independent authority (checked {val.get('checked','')}).")
        L.append(f"- **{r} of {t}** listed vessels resolve in the GFW registry SeaVigil queries; the "
                 f"other **{t - r}** predate or evade AIS, the dark fleet the SAR layer targets, not an "
                 f"AIS-layer miss.")
        L.append(f"- **{na} of {r}** resolved vessels have no current fishing authorization, so SeaVigil "
                 f"grades them unauthorized: **recall on the AIS-visible IUU fleet is {na}/{r}**.")
        L.append(f"- **{it}** are independently tagged `IUU` in GFW's registry, corroborating CCAMLR.\n")
    else:
        L.append("_Run `scripts/validate_iuu.py` (needs GFW_TOKEN) to populate this._\n")

    L.append("## Precision of the IUU cross-reference\n")
    if xref:
        imo, al = xref["recall_by_imo"], xref["recall_by_alias_name"]
        ncr, nc = xref["name_collision_risk"], xref["negative_control"]
        L.append(f"- Strong-identifier (IMO) matching: **{imo['hit']}/{imo['total']}** recall on the "
                 f"listed fleet, **{nc['strong_false_positives']}** false positives on a "
                 f"{nc['size']}-vessel legitimate control.")
        L.append(f"- Name matching reaches **{al['hit']}/{al['total']}** aliases, but "
                 f"**{ncr['generic_aliases']} of {ncr['of_aliases']}** aliases are short generic words "
                 f"that could collide with unrelated vessels, so a name-only match is surfaced as "
                 f"\"verify\", not asserted.\n")
    else:
        L.append("_Run `scripts/measure_iuu_xref.py` to populate this._\n")

    L.append("## The deployed system discriminates (it does not flag everything)\n")
    L.append(f"Authorization grading across **{tot}** real monitored incidents:\n")
    L.append("| status | count | share |")
    L.append("|---|---|---|")
    for k, v in auth.most_common():
        L.append(f"| {k} | {v} | {round(100 * v / tot) if tot else 0}% |")
    L.append(f"\n**{round(100 * cleared / tot) if tot else 0}%** are cleared (authorized, or in their "
             f"own EEZ) and **{round(100 * flagged / tot) if tot else 0}%** are foreign with no "
             "authorization on record and flagged for review. The layer separates the two; it is not a "
             "blanket flag.\n")

    L.append("## The honest bound\n")
    L.append("The **true false-positive rate of the authorization layer cannot be measured from public "
             "data**: national EEZ fishing licences are not public, so \"no authorization on record\" can "
             "mean *unlicensed* or *licensed under a record we cannot see*. That is exactly why SeaVigil "
             "outputs prioritized leads, not proof, and why a human verifies before any enforcement. Full "
             "event-level precision and recall would need a labelled set of confirmed IUU events with "
             "positions and times, plus a matched legitimate control with their licences known; that "
             "dataset is not public.\n")

    L.append("## Reproduce\n")
    L.append("- Recall on IUU vessels: `uv run python scripts/validate_iuu.py` (needs GFW_TOKEN)")
    L.append("- IUU cross-reference precision/recall: `uv run python scripts/measure_iuu_xref.py`")
    L.append("- This summary: `uv run python scripts/build_measurement.py`")
    return "\n".join(L) + "\n"


if __name__ == "__main__":
    main()
